name: Build SileoRU deb

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install deps
      run: |
        sudo apt update
        sudo apt install -y git make clang lld ldid dpkg-dev fakeroot curl perl unzip

    - name: Install Theos
      run: |
        git clone --recursive https://github.com/theos/theos.git $HOME/theos
        echo "THEOS=$HOME/theos" >> $GITHUB_ENV

    - name: Install SDKs
      run: |
        cd $HOME/theos/sdks
        git clone https://github.com/theos/sdks.git

    - name: Build
      run: |
        export THEOS=$HOME/theos
        make clean
        make package

    - name: Upload deb
      uses: actions/upload-artifact@v4
      with:
        name: SileoRU-deb
        path: packages/*.deb
